import { Metadata } from "next";

export const metadata: Metadata = {
    title: "JFM Pricing Page",
    description: "Generated by me, pricing",
    keywords: ['Pricing page', 'JFM', '...'],
};

export default function PricingPage() {
    return (
        <>
            <span className="text-7xl">Pricing Page</span>
        </>
    )
}
