import { Metadata } from "next";

export const metadata: Metadata = {
    title: "JFM Contact Page",
    description: "Generated by me, contact",
    keywords: ['Contact page', 'JFM', '...'],
};

export default function ContactPage() {
    return (
        <>
            <span className="text-7xl">Contact Page</span>
        </>
    )
}
